import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Button, Box, Container, useColorModeValue } from "@chakra-ui/react";
import Navbar from "@/components/navbar";

//import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Yağız Ceritoğlu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Container>{children}</Container>
      </main>
    </>
  );
}
